name: Run Scanner

on:
  schedule:
    - cron: "0 13 * * *"
jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install yfinance pandas ta

      - name: Run scanner
        run: python scanner.py


